# Generated by Django 5.1.1 on 2026-07-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='Identifies which conversation/session this message belongs to.', max_length=100)),
                ('user_message', models.TextField(help_text='The message sent by the user.')),
                ('ai_response', models.TextField(help_text="The AI assistant's reply to the user.")),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('te', 'Telugu')], default='en', help_text='Language this conversation exchange was conducted in.', max_length=5)),
                ('is_emergency', models.BooleanField(default=False, help_text='True if this message triggered emergency detection.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Chat History',
                'verbose_name_plural': 'Chat Histories',
                'ordering': ['created_at'],
            },
        ),
    ]
