# Generated by Django 5.1.1 on 2026-07-18 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chathistory',
            name='session_id',
        ),
        migrations.AddField(
            model_name='chathistory',
            name='user',
            field=models.ForeignKey(default=1, help_text='The patient account this message belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
