# Generated by Django 5.1.1 on 2026-07-18 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(help_text='Name of the medicine (e.g., Paracetamol).', max_length=150)),
                ('dosage', models.CharField(blank=True, help_text="Optional dosage info (e.g., '500mg', '1 tablet').", max_length=100)),
                ('reminder_time', models.TimeField(help_text='Time of day to take this medicine.')),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('twice_daily', 'Twice Daily'), ('thrice_daily', 'Thrice Daily'), ('weekly', 'Weekly'), ('as_needed', 'As Needed')], default='daily', help_text='How often this medicine should be taken.', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this reminder is currently active (patient can pause without deleting).')),
                ('notes', models.TextField(blank=True, help_text="Optional notes (e.g., 'take with food').")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='The patient this reminder belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reminder',
                'verbose_name_plural': 'Reminders',
                'ordering': ['reminder_time'],
            },
        ),
    ]
