# Generated by Django 5.1.1 on 2026-07-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reminder',
            options={'ordering': ['medicine_name'], 'verbose_name': 'Reminder', 'verbose_name_plural': 'Reminders'},
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='reminder_time',
        ),
        migrations.AddField(
            model_name='reminder',
            name='times',
            field=models.CharField(default=1, help_text='Comma-separated reminder times (HH:MM), count matching frequency.', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reminder',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Daily (1 time)'), ('twice_daily', 'Twice Daily (2 times)'), ('thrice_daily', 'Thrice Daily (3 times)')], default='daily', help_text='How often this medicine should be taken.', max_length=20),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this reminder is currently active.'),
        ),
    ]
