# Generated by Django 5.1.1 on 2026-07-18 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='The uploaded PDF or image file.', upload_to='reports/')),
                ('original_filename', models.CharField(help_text='Original name of the uploaded file.', max_length=255)),
                ('extracted_text', models.TextField(blank=True, help_text='Raw text extracted from the file (via PyPDF2 or OCR).')),
                ('ai_explanation', models.TextField(blank=True, help_text="Gemini's simplified explanation of the report.")),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', help_text='Processing status of this report.', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='The patient who uploaded this report.', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
