# Generated by Django 5.1.1 on 2026-07-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(help_text='Full name of the patient booking the appointment.', max_length=150)),
                ('doctor_name', models.CharField(help_text='Name of the doctor for this appointment.', max_length=150)),
                ('appointment_date', models.DateField(help_text='Date of the appointment.')),
                ('appointment_time', models.TimeField(help_text='Time of the appointment.')),
                ('reason', models.TextField(help_text='Reason for the appointment (e.g., symptoms, checkup).')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', help_text='Current status of this appointment.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'ordering': ['appointment_date', 'appointment_time'],
            },
        ),
    ]
