# Generated by Django 5.1.1 on 2026-07-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Official name of the hospital/clinic.', max_length=200)),
                ('address', models.CharField(help_text='Street address.', max_length=300)),
                ('city', models.CharField(help_text='City the hospital is located in.', max_length=100)),
                ('latitude', models.FloatField(help_text='Latitude coordinate (auto-filled via geocoding).')),
                ('longitude', models.FloatField(help_text='Longitude coordinate (auto-filled via geocoding).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hospital',
                'verbose_name_plural': 'Hospitals',
                'ordering': ['name'],
            },
        ),
    ]
