# Generated by Django 5.1.1 on 2026-07-18 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text="Doctor's full name (e.g., Dr. Ramesh Kumar).", max_length=150)),
                ('specialization', models.CharField(choices=[('general_physician', 'General Physician'), ('cardiologist', 'Cardiologist'), ('dermatologist', 'Dermatologist'), ('pediatrician', 'Pediatrician'), ('orthopedic', 'Orthopedic'), ('ent', 'ENT Specialist'), ('gynecologist', 'Gynecologist'), ('neurologist', 'Neurologist'), ('psychiatrist', 'Psychiatrist'), ('dentist', 'Dentist')], help_text="Doctor's medical specialization.", max_length=50)),
                ('available_from', models.TimeField(help_text='Start of working hours (e.g., 09:00).')),
                ('available_to', models.TimeField(help_text='End of working hours (e.g., 17:00).')),
                ('available_days', models.CharField(default='0,1,2,3,4', help_text='Comma-separated weekday numbers doctor is available (0=Mon...6=Sun). Default: Mon-Fri.', max_length=20)),
                ('years_of_experience', models.PositiveIntegerField(default=0, help_text='Years of professional experience.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this doctor is currently accepting appointments.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(help_text='The hospital this doctor practices at.', on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='hospitals.hospital')),
                ('user', models.OneToOneField(help_text='The login account associated with this doctor.', on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
                'ordering': ['full_name'],
            },
        ),
    ]
